In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [33]:
data = pd.read_csv('Churn_Modelling.csv')

In [34]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [43]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
Data_En =LabelEncoder()
Data_En2 =LabelEncoder()
One_h = OneHotEncoder(categorical_features=[1])

In [50]:
data['Geography'] = Data_En.fit_transform(data['Geography'])
data['Gender'] = Data_En2.fit_transform(data['Gender'])
X = data.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1).values
y = data['Exited'].values

In [51]:
X = One_h.fit_transform(X).toarray()
X = X[:,1:]
X

C:\Users\kanis\Anaconda3\envs\py3-TF2.0\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [49]:
from sklearn.preprocessing import StandardScaler
Sc = StandardScaler()
X = Sc.fit_transform(X)
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [52]:
from sklearn.model_selection import train_test_split


In [53]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

In [72]:
import tensorflow
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [73]:
model = Sequential()

In [80]:
num_layers = 10
num_input = 11
model.add(Dense(units=num_layers , kernel_initializer = 'uniform', activation = 'relu', input_dim = num_input))
model.add(Dense(units=num_layers , kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units=1 , kernel_initializer = 'uniform', activation = 'sigmoid'))

In [81]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [84]:
model.fit(X_train, y_train, batch_size = 10, epochs = 10)

Train on 7000 samples
Epoch 1/10
7000/7000 [==============================] - 1s 197us/sample - loss: 0.5111 - accuracy: 0.7924
Epoch 2/10
7000/7000 [==============================] - 2s 247us/sample - loss: 0.5111 - accuracy: 0.7924
Epoch 3/10
7000/7000 [==============================] - 2s 240us/sample - loss: 0.5110 - accuracy: 0.7924
Epoch 4/10
7000/7000 [==============================] - 1s 200us/sample - loss: 0.5112 - accuracy: 0.7924
Epoch 5/10
7000/7000 [==============================] - 1s 192us/sample - loss: 0.5111 - accuracy: 0.7924
Epoch 6/10
7000/7000 [==============================] - 1s 191us/sample - loss: 0.5112 - accuracy: 0.7924
Epoch 7/10
7000/7000 [==============================] - 1s 201us/sample - loss: 0.5114 - accuracy: 0.7924
Epoch 8/10
7000/7000 [==============================] - 1s 200us/sample - loss: 0.5112 - accuracy: 0.7924
Epoch 9/10
7000/7000 [==============================] - 1s 198us/sample - loss: 0.5112 - accuracy: 0.7924
Epoch 10/10
7000/7000 [=

In [85]:
model.predict(X_test)

array([[0.20546854],
       [0.20546854],
       [0.20546854],
       ...,
       [0.20546854],
       [0.20546854],
       [0.20546854]], dtype=float32)

In [87]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)

In [ ]:
grid_search = grid_search.fit(X_train, y_train) 
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_